# Generated by Django 4.1.2 on 2022-11-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoAnfibio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosanfibio',
            name='codigoUsr',
            field=models.CharField(default='OP-0000', max_length=64),
        ),
    ]
